version: "2.27.1-desktop.1"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8080:9000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=product_info
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_info
    volumes:
      - ./data/db:/var/lib/mysql

